<a href="https://colab.research.google.com/github/MANISH-KUMAR-CODES/Daily-code-practice/blob/main/Daily_code_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **In this notebook i will daily practice some codes. so  i never forget how to code and make myself strong in codings**

## practice on one hot encoding using python

In [1]:
import pandas as pd

In [8]:
df= pd.DataFrame({'Team' :["A","A","B","B","B","B","C","C","C"],
                    'points':[25,12,15,14,19,23,25,29,30]})
#view DataFrame
print(df)

  Team  points
0    A      25
1    A      12
2    B      15
3    B      14
4    B      19
5    B      23
6    C      25
7    C      29
8    C      30


In [39]:
from sklearn.preprocessing import OneHotEncoder
#creating instance of one-hot-encoder
Encoder = OneHotEncoder(handle_unknown = 'ignore')

#perform one-hot encoding on 'team' column 
encoder_df = pd.DataFrame(Encoder.fit_transform(df[['Team']]).toarray()) # in fir transform we have to put a dataframe only ,we cannot put a series 

#merge one-hot encoded columns back with original DataFrame
final_df = df.join(encoder_df)

#view final df
print(final_df)

#drop 'team' column
final_df.drop('Team',axis = 1,inplace = True)

#view final df
print(final_df)

final_df.columns = ['points','TeamA','TeamB','TeamC']

  Team  points    0    1    2
0    A      25  1.0  0.0  0.0
1    A      12  1.0  0.0  0.0
2    B      15  0.0  1.0  0.0
3    B      14  0.0  1.0  0.0
4    B      19  0.0  1.0  0.0
5    B      23  0.0  1.0  0.0
6    C      25  0.0  0.0  1.0
7    C      29  0.0  0.0  1.0
8    C      30  0.0  0.0  1.0
   points    0    1    2
0      25  1.0  0.0  0.0
1      12  1.0  0.0  0.0
2      15  0.0  1.0  0.0
3      14  0.0  1.0  0.0
4      19  0.0  1.0  0.0
5      23  0.0  1.0  0.0
6      25  0.0  0.0  1.0
7      29  0.0  0.0  1.0
8      30  0.0  0.0  1.0


In [37]:
#view final df
print(final_df)

   points  TeamA  TeamB  TeamC
0      25    1.0    0.0    0.0
1      12    1.0    0.0    0.0
2      15    0.0    1.0    0.0
3      14    0.0    1.0    0.0
4      19    0.0    1.0    0.0
5      23    0.0    1.0    0.0
6      25    0.0    0.0    1.0
7      29    0.0    0.0    1.0
8      30    0.0    0.0    1.0


In [29]:
Encoder.fit_transform(df[['Team']]).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

### **using split function of python**

In [5]:
x,y = input('Enter two Inputs:').split(",")
print("Number of boys:",x)
print("Number of girls:", y)

Enter two Inputs:45,67
Number of boys: 45
Number of girls: 67


In [16]:
x,y,z = input("Taking three inputs:").split(",")
print("No. of boys:",(x))
print("No. of girls",(y))
print("No. of teachers:",(z))
print("No. of students in total:",x+y+z)

Taking three inputs:444,555,66
No. of boys: 444
No. of girls 555
No. of teachers: 66
No. of students in total: 44455566


In [18]:
a,b = input("The two numbers are:").split(',')
print("First number is {} and second number is {}".format(a,b))

The two numbers are:45,56
First number is 45 and second number is 56


In [23]:
# taking multiple inputs at a time 
# and type casting using list() function
x = list(map(int,input("multiple inputs:").split(',')))
print("list of multiple inputs are:",x)

multiple inputs:46,235,35,35,34,23
list of multiple inputs are: [46, 235, 35, 35, 34, 23]


In [25]:
print("Geeks of Geeks \n is the best for Dsa content")
print("Geeks of geeks \n is the best for DSA", end = '**')
print('Geeks of geeks is the best')

Geeks of Geeks 
 is the best for Dsa content
Geeks of geeks 
 is the best for DSA**Geeks of geeks is the best


### **code to print in same line**

In [27]:
print('Geeks',end = ' ')
print("GeeksofGeeks")

Geeks GeeksofGeeks


In [31]:
a= [1,2,3,4,5]
for i in range(5):
   print(a[i],end =' ')

1 2 3 4 5 

In [36]:
l = [1,2,3,45,6,7]
print(*l)

1 2 3 45 6 7


In [39]:
print('Red',"Blue","Green", sep = ",",end = '@')
print('GeeksforGeeks')

Red,Blue,Green@GeeksforGeeks


In [47]:
# using format() method with number
print("Geeks :{0:2d}, Portal :{1:8.2f}".
      format(1200, 555.546))

Geeks :1200, Portal :  555.55


In [51]:
tab = {'geeks': 4127, 'for': 4098, 'geek': 8637678}

print('Geeks: {0[geeks]:2d}; For: {0[for]:d}; '
    'Geeks: {0[geek]:d}'.format(tab))

Geeks: 4127; For: 4098; Geeks: 8637678


In [55]:
data = dict(fun ="GeeksForGeeks", adj ="Portal")
 
# using format() in dictionary
print("I love {fun} computer {adj}".format(**data))

I love GeeksForGeeks computer Portal


In [64]:
cstr = "I love geeksforgeeks"
print("Centre alingned")
print(cstr.center(40,"*"))
#left alingned
print(cstr.ljust(40,'*'))
#right alinged
print(cstr.rjust(40,"*"))

Centre alingned
**********I love geeksforgeeks**********
I love geeksforgeeks********************
********************I love geeksforgeeks


In [65]:
# Examples of Bitwise operators
a = 10
b = 4
 
# Print bitwise AND operation
print(a & b)
 
# Print bitwise OR operation
print(a | b)
 
# Print bitwise NOT operation
print(~a)
 
# print bitwise XOR operation
print(a ^ b)
 
# print bitwise right shift operation
print(a >> 2)
 
# print bitwise left shift operation
print(a << 2)

0
14
-11
14
2
40


In [2]:
a ,b= 10, 20
if a >b :
  print("a is greater than b")
else:
    print(" b is greater than a")

 b is greater than a


In [5]:
print(a," is greater than b")if (a>b) else print(b," is greater")

20  is greater


In [6]:
print(1 + 2 + 5)
 
# concatenate two strings
print("Geeks"+"For"+ "Geeks")
 
# Product two numbers
print(3 * 4 * 9)
 
# Repeat the String
print("Geeks"*4+5*"for")

8
GeeksForGeeks
108
GeeksGeeksGeeksGeeksforforforforfor


In [29]:
## to overload an binary + operator
class A:
     def __init__(self,a,b):
        self.a = a
        self.b = b

     def __add__(self , o):
        self.o = o
        return self.a + o.a   

In [30]:
obj1 = A(1,5)
obj2 = A(2,4)
print(obj1 + obj2)

3


In [36]:

# A Sample class with init method
class Person:
   
    # init method or constructor 
    def __init__(self, name,age):
        self.age = age
        self.name = name
   
    # Sample Method 
    def say_hi(self):
        print('Hello, my name is {},and my age is {}'.format(self.name,self.age))

In [37]:
p = Person('Nikhil',35)
p.say_hi()

Hello, my name is Nikhil,and my age is 35


In [14]:
class Dog:
     animal = "dog"
     def __init__(self,breed,color):
        self.breed = breed
        self.color = color

     def setcolor(self,color):
         self.color = color

     def getcolor(self):
         return self.color       

     print(Dog.animal)  ##Class variables can be accessed using class

dog


In [6]:
# Objects of Dog class
Rodger = Dog("Pug", "brown")
Buzo = Dog("Bulldog", "black")

In [7]:
print("Rodger details:")
print("Rodger class:",Rodger.animal)
print("Rodger breed:",Rodger.breed)
print("Rodger color:",Rodger.color)

Rodger details:
Rodger class: dog
Rodger breed: Pug
Rodger color: brown


In [8]:
print("Buzo details:")
print("Buzo class:",Buzo.animal)
print("Buzo breed:",Buzo.breed)
print("Buzo color:",Buzo.color)

Buzo details:
Buzo class: dog
Buzo breed: Bulldog
Buzo color: black


In [16]:
Rodger = Dog('Pug','yellow')
Rodger.setcolor("green")
print(Rodger.getcolor())

green


In [18]:
class GeekForGeeks:
      def __init__(self):
         self.geek = "GeekForGeeks"

      def printGeek(self):
          return print(self.geek)

In [19]:
obj = GeekForGeeks()
obj.printGeek()

GeekForGeeks


In [29]:
class Addition:
      first = 0
      second = 0
      answer = 0
      def __init__(self,f,s):
          self.first = f
          self.second = s
           
      def display(self):
        print("First number = " + str(self.first))
        print("Second number = " + str(self.second))
        print("Addition of two numbers = " + str(self.answer))     

      def calculate(self):
          self.answer = (self.first + self.second )
          return print("The answer is:",self.answer)  


In [30]:
obj = Addition(19,56)
obj.calculate()
obj.display()

The answer is: 75
First number = 19
Second number = 56
Addition of two numbers = 75


## **Inheritance in python oops**

In [7]:
class person(object):
      def __init__(self,name):
         self.name = name

      def getname(self):
          return self.name  

      def isemployee(self):
          return False  

class employee(person):
     def isemployee(self):
        return True             

In [9]:
obj = person("mahesh")
print(obj.getname(),obj.isemployee())
obj = employee("bupesh")
print(obj.getname(),obj.isemployee())

mahesh False
bupesh True


In [15]:
class person(object):
    def __init__(self,name,person_id):
        self.name = name 
        self.person_id = person_id

    def display(self):
        print(self.name,self.person_id,self.salary,self.department)    

class employee(person):
      def __init__(self,name,person_id,salary,department):
          self.salary = salary
          self.department= department

          person.__init__(self,name,person_id)
            

In [16]:
a = employee("mahesh",23,300000,"health")
a.display()

mahesh 23 300000 health


In [23]:
class base1():
     def __init__(self):
        self.str1 = "geek1"
        self.str3 = "For"
        print("base1")
class base2():
     def __init__(self):
        self.str2 = "geek2"
        print("base2")

class derived(base1,base2):
      def __init__(self):
          base1.__init__(self)
          base2.__init__(self)
          print("derived")

      def printstrs(self):
          print(self.str1,self.str3,self.str2)    

In [24]:
obj = derived()
obj.printstrs()

base1
base2
derived
geek1 For geek2


In [29]:
class base(object):
     def __init__(self,name):
         self.name = name

     def getname(self):
         return self.name

class child(base):
     def __init__(self,name,age):
       self.age = age
       base.__init__(self,name)

     def getage(self):
         return self.age

class grandchild(child):
     def __init__(self,name,age,address):
        self.address = address
        child.__init__(self,name,age) 

     def getaddress(self):
         return self.address


In [30]:
a = grandchild("mojhan",23,"bhagalpur")
print(a.getname(),a.getage(),a.getaddress())

mojhan 23 bhagalpur


In [50]:
class Child1:
    def __init__(self, name):
        self.name = name
    def getName(self):
        return self.name
    def isStudent(self):
        return False

class Student1(Child1):
    def isStudent(self):
        return True

In [56]:
a = Child1("mohan")
print(a.getName(),a.isStudent())
a = Student1('Rakesh')
print(a.getName(),a.isStudent())

mohan False
Rakesh True


In [72]:
class mother:
      mothername = ""
      def mother(self):
         print(self.mothername)

class father:
      fathername = ""
      def father(self):
         print(self.fathername)

class child(mother,father):
      def parents(self):
          print("Father :", self.fathername)
          print("Mother :", self.mothername)
       

In [74]:
a = child()
a.fathername = "Ram"
a.mothername = "sita"
a.parents()

Father : Ram
Mother : sita


In [75]:
class Grandfather:
 
    def __init__(self, grandfathername):
        self.grandfathername = grandfathername
 
# Intermediate class
class Father(Grandfather):
    def __init__(self, fathername, grandfathername):
        self.fathername = fathername
 
        # invoking constructor of Grandfather class
        Grandfather.__init__(self, grandfathername)
 
# Derived class
class Son(Father):
    def __init__(self,sonname, fathername, grandfathername):
        self.sonname = sonname
 
        # invoking constructor of Father class
        Father.__init__(self, fathername, grandfathername)
 
    def print_name(self):
        print('Grandfather name :', self.grandfathername)
        print("Father name :", self.fathername)
        print("Son name :", self.sonname)

In [76]:
s1 = Son('Prince', 'Rampal', 'Lal mani')
print(s1.grandfathername)
s1.print_name()

Lal mani
Grandfather name : Lal mani
Father name : Rampal
Son name : Prince


In [1]:
class India():
    def capital(self):
        print("New Delhi is the capital of India.")
 
    def language(self):
        print("Hindi is the most widely spoken language of India.")
 
    def type(self):
        print("India is a developing country.")
 
class USA():
    def capital(self):
        print("Washington, D.C. is the capital of USA.")
 
    def language(self):
        print("English is the primary language of USA.")
 
    def type(self):
        print("USA is a developed country.")

In [2]:
obj_ind = India()
obj_usa = USA()
for country in (obj_ind, obj_usa):
    country.capital()
    country.language()
    country.type()

New Delhi is the capital of India.
Hindi is the most widely spoken language of India.
India is a developing country.
Washington, D.C. is the capital of USA.
English is the primary language of USA.
USA is a developed country.


In [3]:
class bird:
     def intro(self):
        print("there are different types of bird")
         
     def flight(self):
        print(" it can fly")

class sparrow(bird):
     def flight(self):
        print("sparrow can fly")

class ostrich(bird):
     def flight(self):
        print("ostrich cannot fly")             

In [6]:
obj_bird = bird()
obj_bird.intro()
obj_bird.flight()

obj_sparrow = sparrow()
obj_sparrow.intro()
obj_sparrow.flight()

obj_ostrich = ostrich()
obj_ostrich.intro()
obj_ostrich.flight()

there are different types of bird
 it can fly
there are different types of bird
sparrow can fly
there are different types of bird
ostrich cannot fly


In [7]:
class India():
    def capital(self):
        print("New Delhi is the capital of India.")
  
    def language(self):
        print("Hindi is the most widely spoken language of India.")
  
    def type(self):
        print("India is a developing country.")
  
class USA():
    def capital(self):
        print("Washington, D.C. is the capital of USA.")
  
    def language(self):
        print("English is the primary language of USA.")
  
    def type(self):
        print("USA is a developed country.")
 
def func(obj):
    obj.capital()
    obj.language()
    obj.type()
  
obj_ind = India()
obj_usa = USA()
  
func(obj_ind)
func(obj_usa)

New Delhi is the capital of India.
Hindi is the most widely spoken language of India.
India is a developing country.
Washington, D.C. is the capital of USA.
English is the primary language of USA.
USA is a developed country.


In [8]:
from datetime import date
 
 
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
 
    # a class method to create a Person object by birth year.
    @classmethod
    def fromBirthYear(cls, name, year):
        return cls(name, date.today().year - year)
 
    # a static method to check if a Person is adult or not.
    @staticmethod
    def isAdult(age):
        return age > 18
 
 
person1 = Person('mayank', 21)
person2 = Person.fromBirthYear('mayank', 1996)
 
print(person1.age)
print(person2.age)
 
# print the result
print(Person.isAdult(22))

21
26
True


### **Try and Except Statement – Catching Exceptions**

In [9]:
def fun(a):
    if a < 4:
 
        # throws ZeroDivisionError for a = 3
        b = a/(a-3)
 
    # throws NameError if a >= 4
    print("Value of b = ", b)
     
try:
    fun(3)
    fun(5)
 
# note that braces () are necessary here for
# multiple exceptions
except ZeroDivisionError:
    print("ZeroDivisionError Occurred and Handled")
except NameError:
    print("NameError Occurred and Handled")

ZeroDivisionError Occurred and Handled


In [1]:
def AbyB(a , b):
    try:
        c = ((a+b) / (a-b))
    except ZeroDivisionError:
        print ("a/b result in 0")
    else:
        print (c)
 

In [2]:
AbyB(2.0, 3.0)
AbyB(3.0, 3.0)

-5.0
a/b result in 0


In [3]:
def division(x, y):
    try:
         result = x//y
         print("the answer is:",result)

    except ZeroDivisionError:
           print("you are diving by zero")      

In [6]:
division(4,0)

you are diving by zero


In [7]:
 
class MyError(Exception):
 
    # Constructor or Initializer
    def __init__(self, value):
        self.value = value
 
    # __str__ is to print() the value
    def __str__(self):
        return(repr(self.value))
 
 
try:
    raise(MyError(3*2))
 
# Value of Exception is stored in error
except MyError as error:
    print('A New Exception occurred: ', error.value)

A New Exception occurred:  6


In [9]:

# define Python user-defined exceptions
class Error(Exception):
   """Base class for other exceptions"""
   pass
class zerodivision(Error):
   """Raised when the input value is zero"""
   pass
try:
   i_num = int(input("Enter a number: "))
   if i_num ==0:
      raise zerodivision
except zerodivision:
   print("Input value is zero, try again!")
   print()

Enter a number: 0
Input value is zero, try again!



In [10]:
class Error(Exception):
     pass
 
class TransitionError(Error):
 
    def __init__(self, prev, nex, msg):
        self.prev = prev
        self.next = nex
 
        self.msg = msg
try:
    raise(TransitionError(2,3*2,"Not Allowed"))

except TransitionError as error:
    print('Exception occurred: ',error.msg)

Exception occurred:  Not Allowed


## **Numpy **

In [1]:
# Python program for
# Creation of Arrays
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)
 
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)
 
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [2]:
import numpy as np
 
# Initial Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)
 
# Printing a range of Array
# with the use of slicing method
sliced_arr = arr[:2, ::2]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)
 
# Printing elements at
# specific Indices
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)

Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [3]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)
 
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array "
       "elements: ", a.sum())
 
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [4]:
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)         

x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype)  
 
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)

Integer Datatype: 
int64

Float Datatype: 
float64

Forcing a Datatype: 
int64


In [8]:
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)\

Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)

Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)

Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr) 

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]

Addition of Array elements: 
19.0

Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]

Transpose of Array: 
[[4. 2.]
 [7. 6.]]


In [9]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [10]:
import numpy as np
 
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)
 
# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)
 
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)
 
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
            "Array type is complex:\n", d)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [11]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
 
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)
 
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
 
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [12]:

a = np.array([1, 2, 5, 3])
 
# add 1 to every element
print ("Adding 1 to every element:", a+1)
 
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
 
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
 
# square each element
print ("Squaring each element:", a**2)
 
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
 
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
 
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [13]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
 
# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
                    arr.max(axis = 1))
 
# minimum element of array
print ("Column-wise minimum elements:",
                        arr.min(axis = 0))
 
# sum of array elements
print ("Sum of all array elements:",
                            arr.sum())
 
# cumulative sum along each row
print ("Cumulative sum along each row:\n",
                        arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [14]:
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])
 
# add arrays
print ("Array sum:\n", a + b)
 
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)
 
# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [15]:
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))
 
# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
 
# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [17]:
arr=[1, 2, 3, 4, 5]
for i in arr:
        print(i)

1
2
3
4
5


In [19]:
import array
arr = array.array('i', [1, 2, 3]) 
 
# printing original array
print ("The new created array is : ",end="")
for i in range (0,3):
    print (arr[i], end=" ")
 
print ("\r")

The new created array is : 1 2 3 


In [20]:
import numpy as geek
 
b = geek.empty(2, dtype = int)
print("Matrix b : \n", b)
 
a = geek.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = geek.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [4607182418800017408 4368955796522032135]

Matrix a : 
 [[                  0 4607182418800017408]
 [4609047870845172685 4610479282544200874]]

Matrix c : 
 [[4.9e-324 2.5e-323 3.0e-323]
 [2.0e-323 3.5e-323 9.9e-324]
 [1.5e-323 4.9e-324 4.4e-323]]


In [21]:
import numpy as geek
 
b = geek.zeros(2, dtype = int)
print("Matrix b : \n", b)
 
a = geek.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = geek.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
import numpy as geek
 
array = geek.arange(8)
print("Original array : \n", array)
 
# shape array with 2 rows and 4 columns
array = geek.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
 
# shape array with 2 rows and 4 columns
array = geek.arange(8).reshape(4 ,2)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
 
# Constructs 3D array
array = geek.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n", array)

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [1]:
import numpy as geek
 
print("A\n", geek.arange(4).reshape(2, 2), "\n")
 
print("A\n", geek.arange(4, 10), "\n")
 
print("A\n", geek.arange(4, 20, 3), "\n")

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



In [2]:
print("B\n", geek.linspace(2.0, 3.0, num=5, retstep=True), "\n")
 
# To evaluate sin() in long range 
x = geek.linspace(0, 2, 10)
print("A\n", geek.sin(x))

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [3]:
array = geek.array([[1, 2], [3, 4]])
 
# using flatten method
array.flatten()
print(array)
 
#using fatten method 
array.flatten('F')
print(array)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [17]:
import numpy as np
a = [[1, 2], [3, 4]]
#using eye 
print(np.eye(4))

print(np.identity(3))

print(np.ones(45))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [23]:
np.arange(56)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [24]:
list1 = [1, 2, 3, 4, 5, 6]
list2 = [10, 9, 8, 7, 6, 5]
 
# Convert list1 into a NumPy array
a1 = np.array(list1)
 
# Convert list2 into a NumPy array
a2 = np.array(list2)
 
print(a1*a2)

[10 18 24 28 30 30]


In [25]:
import numpy as np

a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a)
 
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [26]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
 
# Index values can be negative.
arr = x[np.array([1, 3, -3])]
print("\n Elements are : \n",arr)


 Elements are : 
 [2 4 7]


In [25]:
import numpy as np
a = np.arange(30)
print("range from 8 to 20 wih step soze of 2:", a[8:20:2],'\n')

print(" count of range from right side with step  size of 2:",a[-30:17:1])

print("\n a[10:]  = ",a[10:])

range from 8 to 20 wih step soze of 2: [ 8 10 12 14 16 18] 

 count of range from right side with step  size of 2: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

 a[10:]  =  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [31]:
a = np.array([[0, 1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10, 11],
              [12, 13, 14, 15, 16, 17],
              [18, 19, 20, 21, 22, 23],
              [24, 25, 26, 27, 28, 29],
              [30, 31, 32, 33, 34, 35]])
             
print("\n Array is:\n ",a)
 
# slicing and indexing
print("\n a[0, 3:5]  = ",a[0, 3:5]) 
 
print("\n a[4:, 4:]  = ",a[4:, 4:])
 
print("\n a[:, 2]  = ",a[:, 2]) 
 
print("\n a[2:;2, ::2]  = ",a[2::2, ::2]) ##As there is step size of 2 in row
                                            # thats why its taking only 2 rowsfirst is [18,19,20...] and [24,25,26...]


 Array is:
  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

 a[0, 3:5]  =  [3 4]

 a[4:, 4:]  =  [[28 29]
 [34 35]]

 a[:, 2]  =  [ 2  8 14 20 26 32]

 a[2:;2, ::2]  =  [[12 14 16]
 [24 26 28]]


In [32]:
a = np.array([[0 ,1 ,2],[3 ,4 ,5 ],
              [6 ,7 ,8],[9 ,10 ,11]])
 
print(a[1:2 ,1:3 ])
print(a[1:2 ,[1,2]])

[[4 5]]
[[4 5]]


In [33]:
a = np.array([10, 40, 80, 50, 100])
print(a[a>50])

[ 80 100]


In [34]:
a = np.array([10, 40, 80, 50, 100])
print(a[a%40==0]**2)

[1600 6400]


In [44]:
b = np.array([[5, 5],[4, 5],[16, 4]])
print(b,"\n")
sumrow = b.sum(1)    # here 1 is axis
print(sumrow,"\n")
print(b[sumrow%10==0])# it means remainder is zero after diving

[[ 5  5]
 [ 4  5]
 [16  4]] 

[10  9 20] 

[[ 5  5]
 [16  4]]


In [60]:
import numpy as np
a = np.arange(16)
print(a,"\n")

a = a.reshape(4,4)
print(a,"\n")

for i in np.nditer(a):
   print(i,"\n")

for x in np.nditer(a, order = 'C'):
    print('Modified array in C-style order:') 
    print(x,"\n")   

for x in np.nditer(a, order = 'F'):
    print('Modified array in F-style order:') 
    print(x,"\n")   

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

0 

1 

2 

3 

4 

5 

6 

7 

8 

9 

10 

11 

12 

13 

14 

15 

Modified array in C-style order:
0 

Modified array in C-style order:
1 

Modified array in C-style order:
2 

Modified array in C-style order:
3 

Modified array in C-style order:
4 

Modified array in C-style order:
5 

Modified array in C-style order:
6 

Modified array in C-style order:
7 

Modified array in C-style order:
8 

Modified array in C-style order:
9 

Modified array in C-style order:
10 

Modified array in C-style order:
11 

Modified array in C-style order:
12 

Modified array in C-style order:
13 

Modified array in C-style order:
14 

Modified array in C-style order:
15 

Modified array in F-style order:
0 

Modified array in F-style order:
4 

Modified array in F-style order:
8 

Modified array in F-style order:
12 

Modified array in F-style order:
1 

Modified array in F-style order

In [61]:
a = np.arange(12)
 
 # shape array with 3 rows and 
# 4 columns 
a = a.reshape(3,4) 
 
print('First array is:') 
print(a)
print()  
 
# Creating second array using 
# array method
print('Second array is:') 
b = np.array([5, 6, 7, 8], dtype = int) 
print(b)  
print() 
 
print('Modified array is:')
for x,y in np.nditer([a,b]): 
    print("%d:%d" % (x,y))

First array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Second array is:
[5 6 7 8]

Modified array is:
0:5
1:6
2:7
3:8
4:5
5:6
6:7
7:8
8:5
9:6
10:7
11:8


In [62]:
import numpy as geek
in_num1 = 10
in_num2 = 11
 
print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2) 
   
out_num = geek.bitwise_and(in_num1, in_num2) 
print ("bitwise_and of 10 and 11 : ", out_num) 

Input  number1 :  10
Input  number2 :  11
bitwise_and of 10 and 11 :  10


In [63]:
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
  
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
   
out_arr = geek.bitwise_and(in_arr1, in_arr2) 
print ("Output array after bitwise_and: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_and:  [  2   0 113]


In [64]:
import numpy as geek
in_num1 = 10
in_num2 = 11
 
print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2) 
   
out_num = geek.bitwise_or(in_num1, in_num2) 
print ("bitwise_or of 10 and 11 : ", out_num) 

Input  number1 :  10
Input  number2 :  11
bitwise_or of 10 and 11 :  11


In [65]:
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
  
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
   
out_arr = geek.bitwise_or(in_arr1, in_arr2) 
print ("Output array after bitwise_or: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_or:  [  3  11 127]


In [66]:
in_num1 = 10
in_num2 = 11
 
print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2) 
   
out_num = geek.bitwise_xor(in_num1, in_num2) 
print ("bitwise_xor of 10 and 11 : ", out_num) 

Input  number1 :  10
Input  number2 :  11
bitwise_xor of 10 and 11 :  1


In [67]:
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
  
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
   
out_arr = geek.bitwise_xor(in_arr1, in_arr2) 
print ("Output array after bitwise_xor: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_xor:  [ 1 11 14]


In [68]:
in_num = 10
print ("Input  number : ", in_num)
   
out_num = geek.invert(in_num) 
print ("inversion of 10 : ", out_num) 

Input  number :  10
inversion of 10 :  -11


In [69]:
in_arr = [2, 0, 25]
print ("Input array : ", in_arr)
   
out_arr = geek.invert(in_arr) 
print ("Output array after inversion: ", out_arr) 

Input array :  [2, 0, 25]
Output array after inversion:  [ -3  -1 -26]


In [70]:
in_num = 5
bit_shift = 2
 
print ("Input  number : ", in_num)
print ("Number of bit shift : ", bit_shift ) 
   
out_num = geek.left_shift(in_num, bit_shift) 
print ("After left shifting 2 bit  : ", out_num) 

Input  number :  5
Number of bit shift :  2
After left shifting 2 bit  :  20


In [71]:
in_arr = [2, 8, 15]
bit_shift =[3, 4, 5]
  
print ("Input array : ", in_arr) 
print ("Number of bit shift : ", bit_shift)
   
out_arr = geek.left_shift(in_arr, bit_shift) 
print ("Output array after left shifting: ", out_arr) 

Input array :  [2, 8, 15]
Number of bit shift :  [3, 4, 5]
Output array after left shifting:  [ 16 128 480]


In [72]:
in_num = 10
 
print ("Input  number : ", in_num)
 
out_num = geek.binary_repr(in_num) 
print ("binary representation of 10 : ", out_num) 

Input  number :  10
binary representation of 10 :  1010


In [73]:
in_arr = [5, -8 ]
  
print ("Input array : ", in_arr) 
 

out_num = geek.binary_repr(in_arr[0])
print("Binary representation of 5")
print ("Without using width parameter : ", out_num) 
 

out_num = geek.binary_repr(in_arr[0], width = 5)
print ("Using width parameter: ", out_num) 
 
print("\nBinary representation of -8")
 

out_num = geek.binary_repr(in_arr[1])
print ("Without using width parameter : ", out_num) 
 

out_num = geek.binary_repr(in_arr[1], width = 5)
print ("Using width parameter : ", out_num) 


Input array :  [5, -8]
Binary representation of 5
Without using width parameter :  101
Using width parameter:  00101

Binary representation of -8
Without using width parameter :  -1000
Using width parameter :  11000


In [74]:
a = np.array([[[1,0,1],
             [0,1,0]],
             [[1,1,0],
             [0,0,1]]])
 
# packing elements of an array
# using packbits() function
b = np.packbits(a, axis=-1)
 
print(b)

[[[160]
  [ 64]]

 [[192]
  [ 32]]]


In [75]:
# creating an array using 
# array function
a = np.array([[2], [7], [23]], dtype=np.uint8)
 
# packing elements of an array
# using packbits() function
b = np.unpackbits(a, axis = 1)
 
print(b)

[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 1 0 1 1 1]]


In [76]:
import numpy as np
import math
 
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
 
Sin_Values = np.sin(in_array)
print ("\nSine values : \n", Sin_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Sine values : 
 [0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]


In [1]:
import numpy as np
import math
 
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
 
cos_Values = np.cos(in_array)
print ("\nCosine values : \n", cos_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Cosine values : 
 [ 1.000000e+00  6.123234e-17  5.000000e-01 -1.000000e+00]


In [2]:
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
 
Sinh_Values = np.sinh(in_array)
print ("\nSine Hyperbolic values : \n", Sinh_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Sine Hyperbolic values : 
 [ 0.          2.3012989   1.24936705 11.54873936]


In [3]:
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
 
cosh_Values = np.cosh(in_array)
print ("\ncosine Hyperbolic values : \n", cosh_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

cosine Hyperbolic values : 
 [ 1.          2.50917848  1.60028686 11.59195328]


In [4]:
import numpy as np
 
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
print ("Input array : \n", in_array)
 
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)
 
 
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
 
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)
 
in_array = [.5538, 1.33354, .71445]
print ("\nInput array : \n", in_array)
 
round_off_values = np.around(in_array, decimals = 3)
print ("\nRounded values : \n", round_off_values)

Input array : 
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded values : 
 [ 0.  2.  2.  4.  4. 10.]

Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0.554 1.334 0.714]


In [5]:
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
print ("Input array : \n", in_array)
 
round_off_values = np.round_(in_array)
print ("\nRounded values : \n", round_off_values)
 
 
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
 
round_off_values = np.round_(in_array)
print ("\nRounded values : \n", round_off_values)
 
in_array = [.5538, 1.33354, .71445]
print ("\nInput array : \n", in_array)
 
round_off_values = np.round_(in_array, decimals = 3)
print ("\nRounded values : \n", round_off_values)

Input array : 
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded values : 
 [ 0.  2.  2.  4.  4. 10.]

Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0.554 1.334 0.714]


In [1]:
import numpy as np
 
in_array = [1, 3, 5]
print ("Input array : ", in_array)
 
out_array = np.exp(in_array)
print ("Output array : ", out_array)

Input array :  [1, 3, 5]
Output array :  [  2.71828183  20.08553692 148.4131591 ]


In [2]:
in_array = [1, 3, 5, 2**8]
print ("Input array : ", in_array)
 
out_array = np.log(in_array)
print ("Output array : ", out_array)
 
 
print("\nnp.log(4**4) : ", np.log(4**4))
print("np.log(2**8) : ", np.log(2**8))

Input array :  [1, 3, 5, 256]
Output array :  [0.         1.09861229 1.60943791 5.54517744]

np.log(4**4) :  5.545177444479562
np.log(2**8) :  5.545177444479562


In [3]:
in_num = 2.0
print ("Input  number : ", in_num)
 
out_num = np.reciprocal(in_num)
print ("Output number : ", out_num)

Input  number :  2.0
Output number :  0.5


In [4]:
# input_array
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]
print ("arr1         : ", arr1)
print ("arr2         : ", arr2)
 
# output_array
out = np.divide(arr1, arr2)
print ("\nOutput array : \n", out)

arr1         :  [2, 27, 2, 21, 23]
arr2         :  [2, 3, 4, 5, 6]

Output array : 
 [1.         9.         0.5        4.2        3.83333333]


In [5]:
import numpy as geek 
 
print("Is Real : ", geek.isreal([1+1j, 0j]), "\n")
 
print("Is Real : ", geek.isreal([1, 0]), "\n")

Is Real :  [False  True] 

Is Real :  [ True  True] 



In [6]:
import numpy as np
 
in_complx1 = 2+4j
out_complx1 = np.conj(in_complx1)
print ("Output conjugated complex number of  2+4j : ", out_complx1)
 
in_complx2 =5-8j
out_complx2 = np.conj(in_complx2)
print ("Output conjugated complex number of 5-8j: ", out_complx2)

Output conjugated complex number of  2+4j :  (2-4j)
Output conjugated complex number of 5-8j:  (5+8j)


In [7]:
  
arr1 = [1, 27000, 64, -1000]
print ("cbrt Value of arr1 : \n", np.cbrt(arr1))
  
arr2 = [1024 ,-128]
print ("\ncbrt Value of arr2 : ", np.cbrt(arr2))

cbrt Value of arr1 : 
 [  1.  30.   4. -10.]

cbrt Value of arr2 :  [10.0793684 -5.0396842]


In [8]:
in_array = [1, 2, 3, 4, 5, 6, 7, 8 ]
print ("Input array : ", in_array)
 
out_array = np.clip(in_array, a_min = 2, a_max = 6)
print ("Output array : ", out_array)

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
Output array :  [2 2 3 4 5 6 6 6]


In [9]:
import numpy as np
 
# converting to lowercase
print(np.char.lower(['GEEKS', 'FOR']))
 
# converting to lowercase
print(np.char.lower('GEEKS'))

['geeks' 'for']
geeks


In [10]:
# splitting a string
print(np.char.split('geeks for geeks'))
 
# splitting a string
print(np.char.split('geeks, for, geeks', sep = ','))

['geeks', 'for', 'geeks']
['geeks', ' for', ' geeks']


In [11]:
import numpy as np
 
# splitting a string
print(np.char.join('-', 'geeks'))
 
# splitting a string
print(np.char.join(['-', ':'], ['geeks', 'for']))

g-e-e-k-s
['g-e-e-k-s' 'f:o:r']


In [12]:
import numpy as np
 
a=np.array(['geeks', 'for', 'geeks'])
 
# counting a substring
print(np.char.count(a,'geek'))
 
# counting a substring
print(np.char.count(a, 'fo'))

[1 0 1]
[0 1 0]


In [13]:
import numpy as np
 
a=np.array(['geeks', 'for', 'geeks'])
 
# counting a substring
print(np.char.rfind(a,'geek'))
 
# counting a substring
print(np.char.rfind(a, 'fo'))

[ 0 -1  0]
[-1  0 -1]


In [14]:
# counting a substring
print(np.char.isnumeric('geeks'))
 
# counting a substring
print(np.char.isnumeric('12geeks'))

False
False


In [16]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [17]:
from numpy import linalg as geek
 
# Creating an array using array 
# function
a = np.array([[1, -2j], [2j, 5]])
 
print("Array is :",a)
 
# calculating an eigen value
# using eigh() function
c, d = geek.eigh(a)
 
print("Eigen value is :", c)
print("Eigen value is :", d)

Array is : [[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]
Eigen value is : [0.17157288 5.82842712]
Eigen value is : [[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]
